# Generated by Django 4.2.7 on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0013_alter_prescription_dosage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='item_type',
            field=models.CharField(
                choices=[
                    ('medication', 'Medication'),
                    ('supplement', 'Supplement'),
                    ('medical_supply', 'Medical Supply'),
                    ('device', 'Medical Device'),
                    ('personal_care', 'Personal Care'),
                    ('wellness', 'Wellness Product'),
                    ('other', 'Other Item'),
                ],
                default='medication',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='medication',
            name='form',
            field=models.CharField(
                blank=True,
                choices=[
                    ('tablet', 'Tablet'),
                    ('capsule', 'Capsule'),
                    ('liquid', 'Liquid'),
                    ('injection', 'Injection'),
                    ('ointment', 'Ointment'),
                    ('inhaler', 'Inhaler'),
                    ('cream', 'Cream'),
                    ('drops', 'Drops'),
                    ('powder', 'Powder'),
                    ('spray', 'Spray'),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='medication',
            name='generic_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='medication',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='medication',
            name='requires_prescription',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medication',
            name='strength',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
