# Generated by Django 4.2.7 on 2026-03-31 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_birthday_wish'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0015_sale_saleitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='line_total',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='medication',
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(default='Walk-in Customer', max_length=200),
        ),
        migrations.AlterField(
            model_name='sale',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_sales', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='pharmacy.prescription'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('walkin', 'Walk-in Customer'), ('patient', 'Patient Sale'), ('prescription', 'Prescription Dispensing')], default='walkin', max_length=20),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='pharmacy.batch'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='stock_movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_item', to='pharmacy.stockmovement'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
