# Generated by Django 4.2.7 on 2026-04-14 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0016_remove_sale_total_amount_remove_saleitem_line_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='stock_movement',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='SaleItem',
        ),
    ]
