# Generated by Django 4.2.7 on 2026-03-30 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAppPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('patients', 'Patients'), ('appointments', 'Appointments'), ('billing', 'Billing & Finance'), ('medical_records', 'Medical Records'), ('laboratory', 'Laboratory'), ('pharmacy', 'Pharmacy'), ('reports', 'Reports & Analytics'), ('staff_management', 'Staff Management'), ('budget', 'Budget & Planning'), ('clinic_settings', 'Clinic Settings'), ('inventory', 'Inventory')], max_length=50)),
                ('access', models.CharField(choices=[('default', 'Default'), ('allow', 'Allow'), ('block', 'Block')], default='default', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_userapppermission',
                'unique_together': {('user', 'app_name')},
            },
        ),
    ]
