# Generated by Django 4.2.7 on 2025-11-05 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_reminder_hours', models.IntegerField(default=48, help_text='Hours before appointment for first reminder')),
                ('second_reminder_hours', models.IntegerField(default=24, help_text='Hours before appointment for second reminder')),
                ('final_reminder_hours', models.IntegerField(default=2, help_text='Hours before appointment for final reminder')),
                ('email_enabled', models.BooleanField(default=True, help_text='Send email reminders')),
                ('sms_enabled', models.BooleanField(default=True, help_text='Send SMS reminders')),
                ('notify_patient', models.BooleanField(default=True, help_text='Send reminders to patients')),
                ('notify_provider', models.BooleanField(default=True, help_text='Send reminders to providers')),
                ('notify_admin', models.BooleanField(default=False, help_text='Send reminders to admin')),
                ('notify_nurse', models.BooleanField(default=False, help_text='Send reminders to nurses')),
                ('notify_receptionist', models.BooleanField(default=True, help_text='Send reminders to receptionists')),
                ('sms_api_key', models.CharField(blank=True, help_text='Twilio/SMS API key', max_length=255)),
                ('sms_api_secret', models.CharField(blank=True, help_text='Twilio/SMS API secret', max_length=255)),
                ('sms_from_number', models.CharField(blank=True, help_text='SMS sender phone number', max_length=20)),
                ('reminder_from_email', models.EmailField(blank=True, help_text='Email address for sending reminders', max_length=254)),
                ('admin_emails', models.TextField(blank=True, help_text='Comma-separated admin emails')),
                ('nurse_emails', models.TextField(blank=True, help_text='Comma-separated nurse emails')),
                ('receptionist_emails', models.TextField(blank=True, help_text='Comma-separated receptionist emails')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reminder Settings',
                'verbose_name_plural': 'Reminder Settings',
            },
        ),
        migrations.CreateModel(
            name='AppointmentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('first', 'First Reminder'), ('second', 'Second Reminder'), ('final', 'Final Reminder')], max_length=10)),
                ('recipient_type', models.CharField(choices=[('patient', 'Patient'), ('provider', 'Provider'), ('admin', 'Admin'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist')], max_length=15)),
                ('method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('scheduled_for', models.DateTimeField(help_text='When to send this reminder')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('message_subject', models.CharField(blank=True, max_length=200)),
                ('message_body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='appointments.appointment')),
            ],
            options={
                'ordering': ['scheduled_for', 'created_at'],
                'indexes': [models.Index(fields=['scheduled_for', 'status'], name='appointment_schedul_b51375_idx'), models.Index(fields=['appointment', 'reminder_type'], name='appointment_appoint_895d66_idx')],
            },
        ),
    ]
