# Generated by Django 4.2.7 on 2025-11-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remindersettings_appointmentreminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remindersettings',
            name='sms_api_key',
        ),
        migrations.RemoveField(
            model_name='remindersettings',
            name='sms_api_secret',
        ),
        migrations.RemoveField(
            model_name='remindersettings',
            name='sms_from_number',
        ),
        migrations.AddField(
            model_name='remindersettings',
            name='sms_provider_note',
            field=models.CharField(blank=True, default='Configure SMS in .env file: SMS_PROVIDER, API keys, etc. See SMS_SETUP_GUIDE.md', help_text='SMS is configured via environment variables (.env file)', max_length=500),
        ),
    ]
