# Generated by Django 4.2.7 on 2025-11-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_remindersettings_sms_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('physiotherapy', 'Physiotherapy'), ('nutrition', 'Nutrition'), ('consultation', 'Consultation'), ('assessment', 'Assessment'), ('treatment', 'Treatment'), ('pharmacy', 'Pharmacy')], max_length=20),
        ),
    ]
