# Generated by Django 4.2.7 on 2025-12-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_assessment_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsigns',
            name='blood_pressure_diastolic',
            field=models.IntegerField(blank=True, help_text='Diastolic BP', null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='blood_pressure_systolic',
            field=models.IntegerField(blank=True, help_text='Systolic BP', null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='heart_rate',
            field=models.IntegerField(blank=True, help_text='Heart rate (BPM)', null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='respiratory_rate',
            field=models.IntegerField(blank=True, help_text='Breaths per minute', null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Temperature in Celsius', max_digits=4, null=True),
        ),
    ]
