# Generated by Django 4.2.7 on 2026-03-16 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_make_vitalsigns_fields_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayWish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year the birthday wish was sent')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_wishes', to='patients.patient')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('patient', 'year')},
            },
        ),
    ]
