# Generated by Django 4.2.7 on 2026-04-14 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_birthday_wish'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysiotherapyClinicalReasoningForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crf_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physiotherapy_crf', to='patients.assessment')),
            ],
        ),
    ]
